---

# Pickup hosts from EC2
# Comment this out for non-EC2 setup

 - hosts: ec2
   connection: local
   gather_facts: False
   vars:
     appserver_count: 2
     webserver_count: 1
     storage_count: 1
     # Environment specific
     env: Production
     group: default_Production # Security group allowing all traffic within VPC and port 22 from everywhere
     volume_name: Production_volume # For NFS store
     key: amkey
     zone: eu-west-1a
     cidr: 172.23.0.0/16
     subnet_cidr: 172.23.2.0/24
   roles:
     - ec2_provision

 - include: setup.yaml
