---

# Pickup hosts from EC2
# Comment this out for non-EC2 setup

 - hosts: ec2
   connection: local
   gather_facts: False
   vars:
     appserver_count: 2
     webserver_count: 2
     storage_count: 1
     env: production
     # Values of the following are based on manual actions on AWS Web Console
     key: amkey
     vpc_id: vpc-899f32ec
     subnet: subnet-4336ed1a
     group: default # Security group allowing all traffic within VPC and port 22 from everywhere
     volume_name: production_volume # For NFS store
   roles:
     - ec2_provision

 - include: setup.yaml
