---

# Pickup hosts from EC2
# Comment this out for non-EC2 setup

 - hosts: ec2
   connection: local
   gather_facts: False
   vars:
     appserver_count: 1
     webserver_count: 1
     storage_count: 1
     # Environment specific
     env: Training
     group: default_Training # Security group allowing all traffic within VPC and port 22 from everywhere
     volume_name: Training_volume # For NFS store
     key: amkey
     zone: eu-west-1b
     cidr: 172.22.0.0/16
     subnet_cidr: 172.22.1.0/24
   roles:
     - ec2_provision

 - include: setup.yaml
