---
# Add Tomcat group
 - name: Setup  tomcat_user  group
   group: name={{ tomcat_user }} gid={{ tomcat_gid }}

# Add Tomcat user, doing this instead of a package to have consistent
# id across hosts and NFS server
 - name: Setup tomcat user
   user: name={{ tomcat_user }} comment="Apache Tomcat" uid={{ tomcat_uid }} group={{ tomcat_user }} shell=/bin/nologin

# Install tomcat  and webapps
 - name: Install tomcat
   yum: pkg={{ item }} state=present
   with_items:
    - "{{ tomcat_ver }}"
    - "{{ tomcat_ver }}-webapps"

# Install NFS utils
 - name: Install NFS client
   yum: pkg=nfs-utils state=present


# Set NFS host
 - name: Derive NFS share location
   set_fact: nfs_share="{{ item }}:{{ export }}"
   with_items: hostvars[groups['storage'][0]]['ansible_eth0']['ipv4']['address'] # Assuming only host


# Mount NFS share
 - name: Mounting NFS share
   mount: name={{ apps_dir }} src={{ nfs_share }} state=mounted fstype=nfs

# Create Persistence dir on NFS share
 - name: Create Persistence dir
   file: dest={{ apps_dir }}/persistence mode=755 owner={{ tomcat_user }} state=directory

# Create Persistence Directory if missing
 - name: Create Persistence Directory
   file: dest=/home/russell state=directory

# Create symlink
 - name: Create Symlink to NFS share
   file: path=/home/russell/persistence src={{ apps_dir }}/persistence state=link

# Deploy the war file
 - name: Copy the war
   copy: src=companyNews.war dest=/usr/share/{{ tomcat_ver }}/webapps/

# Remove the health check, created on master shortly after
 - name: Remove health check
   file: path=/usr/share/{{ tomcat_ver }}/webapps/ROOT/status.html state=absent

# Delete examples etc..
 - name: Delete unecessary stuff
   file: path=/usr/share/{{ tomcat_ver }}/webapps/{{ item }} state=absent
   with_items: [sample,examples]
 
# Start Tomcat and enable at startup
 - name: Ensure tomcat is running and enable it
   service: name={{ tomcat_ver }} state=started enabled=yes
#   when: host is master, figure out from the ec2 tag
