---
# Creating a VPC named Assignment
# A separate subnet for each environment - in case we need more like prod,test
   - name: Create new subnet
     ec2_vpc:
       state: present
       cidr_block: "{{ cidr }}"
       resource_tags: { "Environment":"Assignment" }
       subnets:
         - cidr: "{{ subnet_cidr }}"
           az: "{{ zone }}"
           resource_tags: { "Environment":"{{ env }}"}
       internet_gateway: True
       route_tables:
         - subnets:
             - "{{ subnet_cidr }}"
           routes:
             - dest: 0.0.0.0/0
               gw: igw
       region: "{{ region }}"
     register: vpc

   - name: Store vpc_id and subnet
     set_fact: 
       vpc_id="{{ vpc['vpc_id'] }}"
       subnet="{{ vpc['subnets'][0]['id'] }}"
