---
   - name: Create new VPC
     ec2_vpc:
       state: present
       cidr_block: 172.30.0.0/16
       resource_tags: { "Environment":"Development" }
       region: "{{ region }}"
# Full creation example with subnets and optional availability zones.
# The absence or presence of subnets deletes or creates them respectively.
   - name: Create new subnet
     ec2_vpc:
       state: present
       cidr_block: 172.22.0.0/16
       resource_tags: { "Environment":"Development" }
       subnets:
         - cidr: 172.22.1.0/24
           az: "{{ region }}a"
         - cidr: 172.22.2.0/24
           az: "{{ region }}b"
         - cidr: 172.22.3.0/24
           az: "{{ region }}c"
       internet_gateway: True
       route_tables:
         - subnets:
             - 172.22.2.0/24
             - 172.22.3.0/24
           routes:
             - dest: 0.0.0.0/0
               gw: igw
         - subnets:
             - 172.22.1.0/24
           routes:
             - dest: 0.0.0.0/0
               gw: igw
       region: "{{ region }}"
     register: vpc
